name: github
on:
  schedule:
    # 设置启动时间，北京时间早上10点，对 UTC时间早上2点 
    - cron : '5 2 * * *'
    - cron : '5 10 * * *'
    - cron : '0 14 * * *'
    - cron : '0 20 * * *'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Install dependencies
      run: |
        docker run -p 8443:8443 normajcooney/github:latest
